name: Prettier Action
description: Automatically runs prettier on all your changes.

author: Conrad Großer <grosserconrad@gmail.com>

inputs:
  commit_message:
    description: Commit message, will be ignored if used with same_commit
    required: false
    default: 'Prettified Code!'
  same_commit:
    description: Update the current commit instead of creating a new one
    required: false
    default: false
  commit_options:
    description: Commit options
    required: false
  file_pattern:
    description: File pattern used for `git add`, can't be used with only_changed!
    required: false
    default: '*'
  prettier_options:
    description: Options for the `prettier` command
    required: false
    default: '--write **/*.js'
  dry:
    description: Running the script in dry mode just shows whether there are files that should be prettified or not
    required: false
    default: false
  prettier_version:
    description: Specific version of prettier (by default just use the latest version)
    required: false
    default: false
  only_changed:
    description: Only prettify files changed in the last commit, can't be used with file_pattern!
    required: false
    default: false

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'award'
  color: 'green'
